repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
    -   id: requirements-txt-fixer
-   repo: local
    hooks:
    -   id: black
        name: black
        language: python
        entry: black
        args: [--line-length=150]
        types: [python]
    -   id: autoflake
        name: autoflake
        entry: >-
          autoflake
          --in-place
          --ignore-init-module-imports
          --remove-all-unused-imports
          --remove-unused-variables
        language: python
        types: [python]
    -   id: flake8
        name: flake8
        language: system
        entry: >-
          flake8
          --max-line-length=150
          --per-file-ignores="__init__.py:E402,F401"
          --ignore=F403,F405,F841,W503,E203
        types: [python]
